travis:
  secure:
    BINSTAR_TOKEN: pE6FSBzwRebJVqNWoMtS6ZDv6eCONEeX8UCm9a06HfW3i7Qg5tGB52iOHtR9MWLm/tK19RV9b3sparNPBwo8MsBcAoW2B2fLWR8rOWgieWY2UkZ3Cw2+rgzyjRmSFYPxU6MxAOv7JxM2MQdx0Hes3wJbkwn7ff1pjlbSEewJM2a3w7OZ1uG0JA8idefNqRcy4dqQ4tAXENGoLf15i58ZjdwTdH3wVg+5J5f5UQopOVt45/BtJ5RaHEyzpT2CLgyRtdXE+0phrojhWr+ya2gWEIWdL1BfuN+y7z67/SG0+VkNh3X61AeHoIq5dcr0tPq2TK1A6lAHKvNp1xjhMdHlS9Mv+IJ11YcMOqB3XpxTgYd0GKzAZTo+eAVNZGs8FvfutADV2mCNLLpi0qct8uBcA9FKbk+Xn5qR3uiwlbVhh/baa7fLm9nUSFg+hL1f4LoyUTseqqnh3t68ZGjBpat+koR9pV/QRew3Yl6nRBSV1VEQDOaKKRm3qcCGD23QKDNAawUGAq+Gf5CdRWE63RbTrJ9G5aoKeDhRev7wJxL3D9vxMrq50RzOGnJd8UsD42gf7I+4rSNFcm9MPbtomcRPD2z2p8pznrZxHY4tab+SotOQqhw3zCM0YiccnmVCJs4dbnCMomEqLTNwtYWqbFoxTluQfplguWiBGqF6fsdL/Tk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
